### ISSUE TITLE
Global option to turn logging on/off?

### ISSUE THREAD

**Issue by kputschko** [dbosak01/logr#1]
Hey David, I'd like to control the logging over several programs, but I can't find an easy way to make that happen.

**Comment by dbosak01** [comment]
You're right.  Good idea.  Let me look into it...

**Comment by dbosak01** [comment]
Thanks for the suggestion, Kevin.  I've implemented this and pushed to github.  The option is called "logr.on", and you can set it like this:  options("logr.on" = TRUE) or options("logr.on" = FALSE).

Also added an option to control the notes globally, ex.: options("logr.notes" = TRUE) or options("logr.notes" = FALSE)

 Will push to CRAN next week after my one month waiting period expires.  It will be in version 1.0.6.

**Comment by dbosak01** [comment]
Published to CRAN.
