### ISSUE TITLE
Gracefully handle errors

### ISSUE THREAD

**Issue by woodwards** [dbosak01/logr#38]
I'm guessing you've tried this, but it would be nice if logr handled errors more gracefully instead of spitting out a huge traceback. Including closing the log perhaps? Thanks for your awesome tool!

**Comment by dbosak01** [comment]
Simon: Actually the traceback was a user request!  Maybe I can put an option to turn it off.  You are right I can probably print the log footer in the function that is trapping the error.  Thanks for your feedback.  I'll try to do something in the next release.

**Comment by woodwards** [comment]
Thank you so much!

**Comment by dbosak01** [comment]
I added a "traceback" parameter to log_open() so you can turn it off if you want.  Also a global option "logr.traceback".  Also am now calling log_close() in the error handler.  Hopefully this won't cause trouble for anyone.  Will be published in the next few days.

**Comment by woodwards** [comment]
Awesome thank you!
