### ISSUE TITLE
Warnings not logging

### ISSUE THREAD

**Issue by dbosak01** [dbosak01/logr#44]
It seems recent versions of R have caused the last.warning variable to not be populated, so that warnings can be logged.  Need to find another way to do this.

**Comment by gowachin** [comment]
I was interested in logging the `message()` output as well and didn't manage to do so, is it caused by the same issue ?

**Comment by dbosak01** [comment]
Investigated this more and still can't figure it out.  It works when running the code line-by-line in RStudio.  But does not work when you source the file.
