### ISSUE TITLE
Can we get option to print only statements  in log_print

### ISSUE THREAD

**Issue by ghareesh** [dbosak01/logr#48]
The verbose  on log path,program path,working directort  etc is space consuming, especially when running scripts every minute.. 
Example:
Log Path: /data/Rprojects/PDS/log_test/log/2022-09-07 08:28:01.log 
Program Path: /data/Rprojects/PDS/pds_production_v1.2.crud_write_usecase2_usecase3_stage.R 
Working Directory: /home/hdw-etl 
User Name: hdw-etl 
R Version: 3.5.0 (2018-04-23) 
Machine: hdop-prd-r.vmware.com x86_64 
Operating System: Linux 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 
Base Packages: stats graphics grDevices utils datasets methods base Other Packages: lubridate_1.7.9 logr_1.3.3 
Log Start Time: 2022-09-07 08:28:01 

Even with compact = True, these verbals are not going. WIll be good to have an option where only texts within log_print is getting logged.. No extra informations

**Comment by dbosak01** [comment]
OK.  Will consider.

**Comment by dbosak01** [comment]
Sorry this took so long to address.  I put an option on log_open() called "header" that allows you to decide whether or not to print the header.  There is a corresponding option on log_close() called "footer" to decide whether to print the footer.  Probably by now you are using another logging package anyway.  But just wanted to let you know this is finally done.
