### ISSUE TITLE
Suggest option to add timestamp to beginning of each log_print

### ISSUE THREAD

**Issue by woodwards-dnz** [dbosak01/logr#49]
Looking at the log of my long job I wish each line had a time stamp so I could see how long things were taking. 

Should be easy to add as an option?

Thanks for an awesome package!

**Comment by dbosak01** [comment]
Hi Simon:
There is already a notes feature that has an elapsed time.  It is on by default.  Is that sufficient, or are you thinking of something else?

![image](https://user-images.githubusercontent.com/41754982/190503324-8d9e5684-f0c5-4e7a-a371-287b82d93ead.png)

**Comment by woodwards-dnz** [comment]
Ahhh ok got it. It's an option in log_open().

Maybe we can change the elapsed time to minutes or hours?

**Comment by dbosak01** [comment]
The elapsed time should be adjusting itself to the most appropriate interval.  I tested seconds and minutes, but not hours.  If you have a long-running job, I'd be curious to know if it is working correctly.

Also very proud to see someone from the land of R using my package.  You Kiwis are awesome!

**Comment by dbosak01** [comment]
Also, put() and log_print() are the same.  One is just shorter and easier to type.
