### ISSUE TITLE
how to enable multiple logr sessions

### ISSUE THREAD

**Issue by mickeyang** [dbosak01/logr#51]
# Background information:

In the R script below, I tried to simulate a pipeline where I have a **parent-level (global)** log session to monitor the overall execution process. In addition, I have a function called *dummy_function* to print out child-level logs for step 1 and step 2, respectively into two different log files other than the global log file.

After step 1 and 2 completed, I printed out "this workflow completed" to the global session "workflow-log-20230425135234.log". 

However, the global log was overwritten, which did not save the first log record - "this workflow started".

My questions are:

1. Is it possible to enable multiple logr sessions at the same time? 

2. How to "park" the global log session while outputting child-level logs and continue printing to the global one when needed?

I look forward to hearing from you. Thanks for your help in advance.

``` r
rm(list = ls())

library(logr)
options("logr.compact" = T)

dummy_function <- function(step_number){
  step_number <- as.character(step_number)
  # open up step logging
  log_open(stringr::str_glue("step-{step_number}-log.log"))
  sep(stringr::str_glue("step {step_number} is triggered."))
  sep(stringr::str_glue("step {step_number} is completed."))
  # close off step logging
  log_close()
}

execution_date_time <- format(Sys.time(), "%Y%m%d%H%M%S")
log_name <- "workflow-log"
file_name <- stringr::str_glue("{log_name}-{execution_date_time}.log")

# wait for 10 seconds to start the workflow
# hence I can compare log file name with actual logging datetime
Sys.sleep(10)

# open up global/workflow log
log_open(file_name)
#> [1] "./log/workflow-log-20230425135234.log"
log_print("this workflow started")
#> [1] "this workflow started"
# step one logging
dummy_function(1)
#> [1] "========================================================================="
#> [1] "step 1 is triggered."
#> [1] "========================================================================="
#> [1] "========================================================================="
#> [1] "step 1 is completed."
#> [1] "========================================================================="
# step two logging
dummy_function(2)
#> [1] "========================================================================="
#> [1] "step 2 is triggered."
#> [1] "========================================================================="
#> [1] "========================================================================="
#> [1] "step 2 is completed."
#> [1] "========================================================================="
# open up global/workflow log again
log_open(file_name)
#> [1] "./log/workflow-log-20230425135234.log"
log_print("this workflow completed")
#> [1] "this workflow completed"
# close off global/workflow log
log_close()
```

<sup>Created on 2023-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dbosak01** [comment]
This is an interesting use case that I hadn't thought of.  I think I know what is going on.  But let me investigate this weekend and I'll get back to you.

**Comment by mickeyang** [comment]
> This is an interesting use case that I hadn't thought of. I think I know what is going on. But let me investigate this weekend and I'll get back to you.

@dbosak01 Thanks a lot for your support.

**Comment by dbosak01** [comment]
You can get everything printing to one log by not closing and reopening the logs like this:

```
rm(list = ls())

library(logr)
options("logr.compact" = T)

dummy_function <- function(step_number){
  step_number <- as.character(step_number)
  # open up step logging
  #log_open(stringr::str_glue("step-{step_number}-log.log"))
  sep(stringr::str_glue("step {step_number} is triggered."))
  sep(stringr::str_glue("step {step_number} is completed."))
  # close off step logging
  #log_close()
}

execution_date_time <- format(Sys.time(), "%Y%m%d%H%M%S")
log_name <- "workflow-log"
file_name <- stringr::str_glue("{log_name}-{execution_date_time}.log")

# wait for 10 seconds to start the workflow
# hence I can compare log file name with actual logging datetime
Sys.sleep(10)

# open up global/workflow log
log_open(file_name)
#> [1] "./log/workflow-log-20230425135234.log"
log_print("this workflow started")
#> [1] "this workflow started"
# step one logging
dummy_function(1)
#> [1] "========================================================================="
#> [1] "step 1 is triggered."
#> [1] "========================================================================="
#> [1] "========================================================================="
#> [1] "step 1 is completed."
#> [1] "========================================================================="
# step two logging
dummy_function(2)
#> [1] "========================================================================="
#> [1] "step 2 is triggered."
#> [1] "========================================================================="
#> [1] "========================================================================="
#> [1] "step 2 is completed."
#> [1] "========================================================================="
# open up global/workflow log again
#log_open(file_name)
#> [1] "./log/workflow-log-20230425135234.log"
log_print("this workflow completed")
#> [1] "this workflow completed"
# close off global/workflow log
log_close()
```

You can get the sub processes printing to their own log by initializing logr inside the dummy_function, like this:
```

dummy_function <- function(step_number){
  
  library(logr)
  options("logr.compact" = T)
  
  step_number <- as.character(step_number)
  # open up step logging
  log_open(stringr::str_glue("step-{step_number}-log.log"))
  sep(stringr::str_glue("step {step_number} is triggered."))
  sep(stringr::str_glue("step {step_number} is completed."))
  # close off step logging
  log_close()
}
```

But so far I can't figure out how to create multiple child logs and keep the global log open using the existing code.  I might need to modify the package to make this work.  Possibly add a function.  

So I guess the answer is logr can't do this right now.  But I like the idea and will consider an enhancement to accommodate.

**Comment by mickeyang** [comment]
Hi @dbosak01 ,
Thanks massively for your reply and looking into my example.

It will be beneficial if you could enhance the package to allow both "parent" and "child" logging sessions at the same time.

I look forward to hearing from you.

Have a good day.

**Comment by dbosak01** [comment]
I thought about this for a long time because some of the possible solutions to this issue would break the package or existing code.  I just put in two functions that can help: log_suspend() and log_resume().  These allow you to open a log, suspend it, call a function that opens another long, and then reopen the first log.  I know this is not an ideal solution.  But, as I say, I worry about breaking people's existing code.  Hope that helps.  I'm going to close this issue for now.  Sorry it took so long to address.
