### ISSUE TITLE
log_code, encodings, windows

### ISSUE THREAD

**Issue by clemenskuehn** [dbosak01/logr#52]
Thank you for your work on the package, first of all!

On a windows machine and RStudio, R 4.0.2, I have characters like "ü" in my comments in an UTF-8 encoded source file, like

`# some ü more text`

when calling 
`log_open()`
`log_code()`
`log_close()`

the log_close() causes a warning:
Warning messages:
1: In readLines(pth, encoding = "UTF-8") :
  invalid input found on input connection './log/test.log'
2: In readLines(pth, encoding = "UTF-8") :
  incomplete final line found on './log/test.log'

and the log file contains code only until before the unusual character.

Likely a problem with encodings of the read/written files. Checking with notepad++, the encoding of the log-file seems to be ANSI, the encoding of the msg-files is UTF-8.

**Comment by dbosak01** [comment]
Thanks for point this issue out.  I believe it.  I struggled with a lot of encoding issues in the past.  I'm out of town this week, but will investigate this issue next week.  Sorry for the inconvenience.

**Comment by clemenskuehn** [comment]
Don't wörry about me, I'll get äround the issüe, also struggling with encödings all däy

**Comment by dbosak01** [comment]
Hmm...  I can't seem to reproduce.  I'm also on Windows, but using R 4.3.1.  There was a change in R related to encodings called "ucrt".  I'm wondering if that is the issue.  Do you have admin rights to the machine you are working on, or is it a work machine with a lot of restrictions on it?  Meaning, can you install things or not?

**Comment by dbosak01** [comment]
Here is my log:
```
=========================================================================
Log Path: C:/packages/Testing/log/encodingtest.log
Program Path: C:/packages/Testing/encodingtest.R
Working Directory: C:/packages/Testing
User Name: dbosa
R Version: 4.3.1 (2023-06-16 ucrt)
Machine: SOCRATES x86-64
Operating System: Windows 10 x64 build 22621
Base Packages: stats graphics grDevices utils datasets methods base Other
Packages: logr_1.3.4
Log Start Time: 2023-11-08 10:06:11.658105
=========================================================================

> library(logr)
> 
> # Here is something
> 
> 
> # some ü more text
> 
> 
> log_open()
> 
> log_code()
> 
> 
> log_close()
> 
> 

=========================================================================
Log End Time: 2023-11-08 10:06:11.68677
Log Elapsed Time: 0 00:00:00
=========================================================================
```

**Comment by clemenskuehn** [comment]
Hi,
thank you for your time!
I am indeed on a multiple machines where I don't have admin rights. One of these is running R 4.3.1, but it still produces the same error.  Also, it is not Windows 10, but Windows Server.

I am a little confused, but I am not at all capable of administrating windows systems and R on windows systems and the encodings-issues they might have on different layers.

I am afraid my issue is a rather specific one that does not really have a sensible tradeoff of time and output. I wouldn't mind if we don't pursue it any further.

**Comment by dbosak01** [comment]
I think I know where the issue is occurring, and it happened to be in a section of code that is no longer needed.  So I've removed this code.  Not sure it will help in your situation or not.  You'll have to try it.  Will push to CRAN shortly.
