### ISSUE TITLE
Warning messages are not output to log file

### ISSUE THREAD

**Issue by Raphael0522** [dbosak01/logr#55]
Hi David, 
I use the below sample program to create TLF program. However, I notice that the warning messages are not written into log file. I suppose the warning message would be output after calling 'log_close' function. Not sure if it's caused by running 'log_close' function in a function. I read the vignette from cran, but not sure about the definition of 'the end of the logging session'. Can you let me know how to use it correctly? 

Thank you!
Raphael

**Vignette from cran:**
Errors are printed at the point at which they occur. But warnings can be captured only at the end of the logging session. Therefore, any warning messages will only be printed at the bottom of the log.

**My test example code**
library(tidyverse)
library(sassy)
# Turn on the log function in Sassy logr package
options("logr.autolog" = TRUE)
# Get temp location for log and report output
logdir <- '~/projects/2693/2693_ma/progs/prod/figures/Pooled_AMNOG_12W'

tryCatch({
  mainfunc <- function(output_fl_name){
    output_full_name <- paste0('test', output_fl_name)  
    
    # Remove msg file before execution
    if (file.exists(file.path(logdir, paste0(output_full_name, ".msg")))){
      file.remove(file.path(logdir, paste0(output_full_name, ".msg")))  
    }     
    # Open the log and message files in a temporary folder - lf_yyyy_mm_dd_hh_mm_ss.log
    log_file <- paste0(output_full_name, ".log")
    msg_file <- paste0(output_full_name, ".msg")
     
    lf <- log_open(file.path(logdir, log_file), logdir = FALSE)   
    # create a vector
    vec1 <- c(1,2,3)    
    # throw a warning 
    warning("test warning message here!!!")
    
    # Send code to the log
    log_code()
    
    # Clean Up -----------------------------------------------------------------
    sep("Clean Up")
  
    # Close the log
    log_close()    
  }

  mainfunc(output_fl_name = '_1')

}, finally = {  
  # End of program  
})

**Comment by dbosak01** [comment]
Yes, I've been fighting with the warnings probably for a year.  There is already an issue opened here #44.  I'll look at it again this weekend, plus your other libr question.

**Comment by dbosak01** [comment]
Super frustrating problem.  You're supposed to be able to get the warning from a variable named "last.warning", but that variable is not available until the program execution has completed.  You're also supposed to be able to hook a callback function into the warning, but that is not working as expected.  It works for errors, but not for warnings. Still investigating, but so far no clear path to success.
