### ISSUE TITLE
Error with log_warning()

### ISSUE THREAD

**Issue by williamthistle** [dbosak01/logr#66]
First, thanks for the great logging package! I use it in a tool I developed and I ran into an error recently with `log_warning()`. Not sure why this happens sometimes, but basically it's possible for `msg` to be `NULL` and `sys.nframe()` to be `0`. When this happens, the logger will fail with:

` "object 'msg1' not found"`

I've made a temporary fix with two updated lines of code (see # UPDATED LINE below) like so:

```
    if (!is.null(msg)) {
      msg1 <- paste("Warning:", msg)
      log_print(msg1, console = FALSE)
      log_quiet(msg1, msg = TRUE)
      message(msg1)
    } else {
      msg1 <- "Warning:" # UPDATED LINE
      for (n in seq.int(to = 1, by = -1, length.out = sys.nframe() - 1)) {
        e1 <- sys.frame(n)
        # print(paste("frame: ", n))
        lse <- ls(e1)
        #print(lse)

        if ("call" %in% lse && "msg" %in% lse) {
          # call1 <- capture.output(print(get("call", envir = e1)))
          # print(msg)
          msg1 <- paste(msg1, get("msg", envir = e1))  # UPDATED LINE
          log_print(msg1, console = FALSE)
          logr:::log_quiet(msg1, msg = TRUE)
          message(msg1)
        }
      }
    }
```

No idea if there's a more elegant way, but this is a rough fix, at least in my scenario. I'm not entirely sure what causes this situation to arise, but it's in a parallel process using `doParallel` if that helps at all.

Thanks again!

**Comment by dbosak01** [comment]
Thanks so much for the notice.  Also not exactly sure what is happening.  I've made an update and pushed to github.  If you have time, let me know if this works.  The version I pushed won't send an "empty" warning.

**Comment by williamthistle** [comment]
I tested the fix and it works - thank you!

**Comment by dbosak01** [comment]
Excellent!  Thanks again for the notice.
